name: Frontend React CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      - name: 📦 Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📦 Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: 🏗️ Validar compilación local
        run: pnpm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Desplegar en VPS vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/alejandrotg/apps/game-recommended
            git pull origin main
            
            pnpm install
            pnpm run build